/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import javax.swing.JComboBox;
import datos.ActivityDAO;
import datos.Activity;
import datos.Period;
import datos.PeriodDAO;
import static java.util.Collections.list;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Panana
 */
public class ConfigurationPanel extends javax.swing.JPanel {

    /**
     * Creates new form jpConfig
     */
    //Verificar si se ha cambiado el limite de cupo de alguna actividad
    private boolean isLimitCupo;
    //Verificar si se esta agregando una nueva actividad
    private boolean isAddNewActivity;

    public ConfigurationPanel() {
        initComponents();
        
        //colocar los registros de actividades en el componente jcbActivities
        ActivityDAO activityDAO = new ActivityDAO();
        List<Activity> activities = activityDAO.select();
        jcbActivities.addItem("-Seleccionar Actividad-");
        for(Activity activity : activities)
        {
            jcbActivities.addItem(activity.getActivityName());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbActivities = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtfCupo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jbAply = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfActivityName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbActivityType = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtfRegisterLimit = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 252, 252));

        jcbActivities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jcbActivities.setToolTipText("Selecionar actividad");
        jcbActivities.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbActivitiesItemStateChanged(evt);
            }
        });

        jLabel1.setText("Establecer limte de cupo");

        jtfCupo.setToolTipText("Establecer limite de cupo");
        jtfCupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCupoActionPerformed(evt);
            }
        });

        jbAply.setText("Aplicar");
        jbAply.setToolTipText("Guardar configuración");
        jbAply.setEnabled(false);
        jbAply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAplyActionPerformed(evt);
            }
        });

        jLabel2.setText("Agregar Actividades");

        jtfActivityName.setToolTipText("Nombre de la actividad a agregar");
        jtfActivityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfActivityNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre: ");

        jLabel4.setText("Tipo de actividad:");

        jcbActivityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Cultural","Deportiva","Civica"}));
        jcbActivityType.setToolTipText("Selecionar el tipo de actividad");
        jcbActivityType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbActivityTypeItemStateChanged(evt);
            }
        });
        jcbActivityType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbActivityTypeActionPerformed(evt);
            }
        });

        jLabel5.setText("Cupo Limite:");

        jtfRegisterLimit.setToolTipText("Establecer un cupo limite");
        jtfRegisterLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRegisterLimitActionPerformed(evt);
            }
        });

        jLabel7.setText("Elegir actividad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbAply, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbActivities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfCupo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(40, 40, 40)
                                .addComponent(jtfRegisterLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbActivityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfActivityName, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbActivities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfActivityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jcbActivityType, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfRegisterLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jbAply)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbAplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAplyActionPerformed

        try 
        {
            //Confirmar que se desean guardar los cambios
            int confirmSave = JOptionPane.showConfirmDialog(null, "¿Guardar cambios?");
            if (confirmSave == 0) 
            {
                //Verificar si se ha modificado el limite del cupo
                if (isLimitCupo) 
                {
                    //Asignar el cupo al objeto activity
                    Activity activity = new Activity(Integer.parseInt(jtfCupo.getText()));
                    //Crear el objeto activityDAO
                    ActivityDAO activityDAO = new ActivityDAO();
                    //Establecer el cupo limite en las actividades
                    activityDAO.update(activity, jcbActivities.getSelectedItem().toString());
                   
                    //desabilitar el boton de aplicar configuracion
                    jbAply.setEnabled(false);
                    //Dar a conocer que ya no se esta realizando ninguna configuracion
                    isLimitCupo = false;
                }
                //Verificar si se esta agregando una nueva actividad
                if(isAddNewActivity)
                {
                    //Crear objeto activity para insertar los datos
                    Activity activity = new Activity(jtfActivityName.getText(),jcbActivityType.getSelectedIndex() + 1,Integer.parseInt(jtfRegisterLimit.getText()));
                    
                    //Crear objecto ActivityDAO para insertar los datos en la bd
                    ActivityDAO activityDAO = new ActivityDAO();
                    activityDAO.insert(activity);
                    //Dar a conocer que ya se ha agregado una nueva actividad
                    isAddNewActivity = false;
                    
                }
                
                 //Mensaje de confirmacion
                JOptionPane.showMessageDialog(null, "¡Configuración guardada!");
                JOptionPane.showMessageDialog(null, "Favor de reinicie el programa para usar la nueva configuración");
            }
            
        } 
        catch (Exception ex) 
        {        

            JOptionPane.showMessageDialog(null, "Verifique los datos");
        }
    }//GEN-LAST:event_jbAplyActionPerformed

    private void jtfCupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCupoActionPerformed
        //Verificar que el jtextField contenga texto
        if(jtfCupo != null)
        {
            //Dar a conocer que se ha realizado un cambio en el limite del cupo
            isLimitCupo = true;
            //habilitar el boton de aplicar configuracion
            jbAply.setEnabled(true);
        }
        
    }//GEN-LAST:event_jtfCupoActionPerformed

    private void jcbActivitiesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbActivitiesItemStateChanged
       try
       {
           //Crear objeto de la clase ActivityDAO
           ActivityDAO activityDAO = new ActivityDAO();
           //Obtener los registros de la tabla de actividades
           List<Activity> activities = activityDAO.select();
           
           //Asignar los nombres de las actividades a jtfCupo
           for(Activity activity : activities)
           {
               if(activity.getActivityName().equals(jcbActivities.getSelectedItem().toString()))
               {
                   //asignar el limite al componente
                   jtfCupo.setText(String.valueOf(activity.getLimit()));
               }
           }
       }
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, ex);
       }
    }//GEN-LAST:event_jcbActivitiesItemStateChanged

    private void jcbActivityTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbActivityTypeItemStateChanged
        isAddNewActivity = true;
       jbAply.setEnabled(true);
    }//GEN-LAST:event_jcbActivityTypeItemStateChanged

    private void jcbActivityTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbActivityTypeActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jcbActivityTypeActionPerformed

    private void jtfActivityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfActivityNameActionPerformed
       //Dar a conocer que se esta agregando el nombre de una nueva actividad
       isAddNewActivity = true;
       jbAply.setEnabled(true);
    }//GEN-LAST:event_jtfActivityNameActionPerformed

    private void jtfRegisterLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRegisterLimitActionPerformed
        isAddNewActivity = true;
       jbAply.setEnabled(true);
    }//GEN-LAST:event_jtfRegisterLimitActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbAply;
    private javax.swing.JComboBox<String> jcbActivities;
    private javax.swing.JComboBox<String> jcbActivityType;
    private javax.swing.JTextField jtfActivityName;
    private javax.swing.JTextField jtfCupo;
    private javax.swing.JTextField jtfRegisterLimit;
    // End of variables declaration//GEN-END:variables
}
